name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install -r cardetect/requirements.txt

    - name: Configure AWS profile
      run: |
        aws configure set region us-east-1 --profile default
        aws configure set output json --profile default
        aws configure set aws_access_key_id ${{ secrets.PRIMARY_AWS_ACCESS_KEY_ID }} --profile default
        aws configure set aws_secret_access_key ${{ secrets.PRIMARY_AWS_SECRET_ACCESS_KEY }} --profile default

    - name: Zappa deployments
      run: |
        cd cardetect
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        zappa update --all
